In [3]:
import numpy as np

A = np.array ([[4,5],[2,6]])
B = np.array([[9,10],[34,88]])

print("The Matrix A is\n", A, "\n And the Matrix B is\n",B)

C = A + B
print("The addition of Matrix A and B results into \n",C)

D = A - B
print("The subtraction of Matrix A and B results into \n",D)

E = A * B
print("The multiplication of Matrix A and B results into \n",E)

F = np.dot(A, B)
print("The Matrix Multiplication of A and B \n",F)

G = A.T
print("The Transpose of Matrix A is \n",G)

H = np.linalg.det(A)
print("The Determinant of Matrix A is \n",H)

if H !=0:
  A_inverse = np.linalg.inv(A)
  print("\nInverse of A\n")
  print(A_inverse)
else:
  print("The Matrix is Singular")


The Matrix A is
 [[4 5]
 [2 6]] 
 And the Matrix B is
 [[ 9 10]
 [34 88]]
The addition of Matrix A and B results into 
 [[13 15]
 [36 94]]
The subtraction of Matrix A and B results into 
 [[ -5  -5]
 [-32 -82]]
The multiplication of Matrix A and B results into 
 [[ 36  50]
 [ 68 528]]
The Matrix Multiplication of A and B 
 [[206 480]
 [222 548]]
The Transpose of Matrix A is 
 [[4 2]
 [5 6]]
The Determinant of Matrix A is 
 14.000000000000004

Inverse of A

[[ 0.42857143 -0.35714286]
 [-0.14285714  0.28571429]]
